/**
 * routes/memory.ts — Session memory endpoints
 *
 * GET    /api/memory/:sessionId          → Fetch a session (creates it if new)
 * PUT    /api/memory/:sessionId/prefs    → Update user preferences
 * DELETE /api/memory/:sessionId          → Clear all memory for a session
 *
 * The session ID is a UUID generated by the frontend and stored in localStorage.
 * This lets the app work without user accounts — each browser has its own identity.
 */

import { Router } from "express";
import {
  getOrCreateSession,
  updatePreferences,
  clearSession,
} from "../lib/memory";
import { logger } from "../lib/logger";

const router = Router();

// ── GET /api/memory/:sessionId ────────────────────────────────────────────────
// Returns the full session memory: messages, summary, preferences, stats.
// Creates a blank session if this ID is new.
router.get("/memory/:sessionId", async (req, res) => {
  const { sessionId } = req.params;

  if (!sessionId || !/^[a-zA-Z0-9\-]{8,64}$/.test(sessionId)) {
    res.status(400).json({ error: "Invalid session ID" });
    return;
  }

  try {
    const session = await getOrCreateSession(sessionId);
    res.json(session);
  } catch (err) {
    logger.error({ err, sessionId }, "Failed to get session");
    res.status(500).json({ error: "Failed to load session" });
  }
});

// ── PUT /api/memory/:sessionId/prefs ─────────────────────────────────────────
// Update user preferences for a session (name, style, etc.).
// Body: { name?: string, [key: string]: string }
router.put("/memory/:sessionId/prefs", async (req, res) => {
  const { sessionId } = req.params;
  const updates = req.body as Record<string, string>;

  if (!sessionId || !updates || typeof updates !== "object") {
    res.status(400).json({ error: "Invalid request" });
    return;
  }

  try {
    const session = await updatePreferences(sessionId, updates);
    res.json(session);
  } catch (err) {
    logger.error({ err, sessionId }, "Failed to update preferences");
    res.status(500).json({ error: "Failed to update preferences" });
  }
});

// ── DELETE /api/memory/:sessionId ─────────────────────────────────────────────
// Clears all messages, summary, and preferences for a session.
// The session ID itself is kept — the user stays on the same session,
// just with a clean slate.
router.delete("/memory/:sessionId", async (req, res) => {
  const { sessionId } = req.params;

  if (!sessionId || !/^[a-zA-Z0-9\-]{8,64}$/.test(sessionId)) {
    res.status(400).json({ error: "Invalid session ID" });
    return;
  }

  try {
    const session = await clearSession(sessionId);
    res.json({ success: true, session });
  } catch (err) {
    logger.error({ err, sessionId }, "Failed to clear session");
    res.status(500).json({ error: "Failed to clear memory" });
  }
});

export default router;
